// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG4nFqiPhrgKampsN-XbU5Br7VGUyft70',
    appId: '1:535481523181:web:8bf39d4eed8bfca88c65e4',
    messagingSenderId: '535481523181',
    projectId: 'healthmate-devx',
    authDomain: 'healthmate-devx.firebaseapp.com',
    storageBucket: 'healthmate-devx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYKg3Aa4Q5p1J7oGva_KiLy95mdrz5dk0',
    appId: '1:535481523181:android:eed7f5b9ddc3511f8c65e4',
    messagingSenderId: '535481523181',
    projectId: 'healthmate-devx',
    storageBucket: 'healthmate-devx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiFRertf9_7XMhR35FCKF7BSyirbSIGBw',
    appId: '1:535481523181:ios:6d32fcbdd9d113328c65e4',
    messagingSenderId: '535481523181',
    projectId: 'healthmate-devx',
    storageBucket: 'healthmate-devx.firebasestorage.app',
    iosBundleId: 'com.devx.healthmate',
  );
}
