import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'login.dart';
import 'register.dart';
import 'patientDashboard.dart'; // Import the patient dashboard
import 'auth_wrapper.dart';
import 'doctorReg.dart';
import 'caregiverReg.dart';
import 'hospitalReg.dart';
import 'screens/doctor_dashboard.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'HealthMate',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      initialRoute: '/',
      onGenerateRoute: (settings) {
        if (settings.name == '/register') {
          return MaterialPageRoute(builder: (_) => const RegisterPage());
        } else if (settings.name == '/') {
          return MaterialPageRoute(builder: (_) => const AuthWrapper());
        } else if (settings.name == '/login') {
          return MaterialPageRoute(builder: (_) => const LoginPage());
        } else if (settings.name == '/patientDashboard') {
          return MaterialPageRoute(builder: (_) => const PatientDashboard());
        } else if (settings.name == '/doctorRegister') {
          return MaterialPageRoute(
            builder: (_) => const DoctorRegistrationPage(),
          );
        } else if (settings.name == '/caregiverRegister') {
          return MaterialPageRoute(
            builder: (_) => const CaregiverRegistrationPage(),
          );
        } else if (settings.name == '/hospitalRegister') {
          return MaterialPageRoute(
            builder: (_) => const HospitalRegistrationPage(),
          );
        } else if (settings.name == '/doctorDashboard') {
          return MaterialPageRoute(builder: (_) => const DoctorDashboard());
        }
        // Handle unknown routes
        return MaterialPageRoute(builder: (_) => const AuthWrapper());
      },
      // Keep the routes map as a fallback
      routes: {
        '/': (context) => const AuthWrapper(),
        '/login': (context) => const LoginPage(),
        '/register': (context) => const RegisterPage(),
        '/patientDashboard': (context) => const PatientDashboard(),
        '/doctorRegister': (context) => const DoctorRegistrationPage(),
        '/caregiverRegister': (context) => const CaregiverRegistrationPage(),
        '/hospitalRegister': (context) => const HospitalRegistrationPage(),
        '/doctorDashboard': (context) => const DoctorDashboard(),
      },
    );
  }
}
