import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'login.dart';
import 'register.dart';
import 'patientDashboard.dart'; // Import the patient dashboard
import 'auth_wrapper.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'HealthMate',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      initialRoute: '/',
      onGenerateRoute: (settings) {
        if (settings.name == '/register') {
          return MaterialPageRoute(builder: (_) => const RegisterPage());
        } else if (settings.name == '/') {
          return MaterialPageRoute(builder: (_) => const AuthWrapper());
        } else if (settings.name == '/login') {
          return MaterialPageRoute(builder: (_) => const LoginPage());
        } else if (settings.name == '/home') {
          return MaterialPageRoute(
            builder: (_) => const MyHomePage(title: 'Flutter Demo Home Page'),
          );
        } else if (settings.name == '/patientDashboard') {
          return MaterialPageRoute(builder: (_) => const PatientDashboard());
        } // Handle unknown routes
        return MaterialPageRoute(builder: (_) => const AuthWrapper());
      },
      // Keep the routes map as a fallback
      routes: {
        '/': (context) => const AuthWrapper(),
        '/login': (context) => const LoginPage(),
        '/home': (context) => const MyHomePage(title: 'Flutter Demo Home Page'),
        '/register': (context) => const RegisterPage(),
        '/patientDashboard': (context) => const PatientDashboard(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
